name: garmin-ai-coach
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - nodejs
  - pip:
      - black
      - cryptography
      - fastapi
      - garminconnect
      - httpx
      - ipykernel
      - jupyterlab
      - matplotlib
      - openai
      - pandas
      - pydantic
      - pypdf
      - pylint
      - playwright
      - pymysql
      - scikit-learn
      - pytest
      - python-dotenv
      - python-multipart
      - sqlalchemy
      - uvicorn
